services:
  mongo:
    image: mongo
    ports:
      - '27017-27017:27017-27017'
    volumes:
      - ./mongo-volume:/data/db

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit-dev
    ports:
      - '5672:5672'
      - '15672:15672'
